### ISSUE TITLE
How does this Codacy extension work?

### ISSUE THREAD

**Issue by mahnoorkazidh** [codacy/codacy-vscode-extension#13]

**Comment by nicklem** [comment]
Hi @mahnoorkazidh! Thanks for reaching out.

The Codacy VS Code extension lists all problems identified by Codacy for a pull request you are working on directly within VS Code and can help you review and fix them.

To use this extension, you need a Codacy account. Additionally, the repository you're working on should be analyzed by Codacy.

You can find more information and [detailed instructions on the Codacy docs](https://docs.codacy.com/getting-started/integrating-codacy-with-visual-studio-code/).

I hope this helps!
Nico
